config/routes.rb
Rails.application.routes.draw do
  resources :drinks

  resources :foods

end

app/models/drink.rb
class Drink < ActiveRecord::Base
end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: [:show, :edit, :update, :destroy]

  # GET /drinks
  # GET /drinks.json
  def index
    @drinks = Drink.all
  end

  # GET /drinks/1
  # GET /drinks/1.json
  def show
  end

  # GET /drinks/new
  def new
    @drink = Drink.new
  end

  # GET /drinks/1/edit
  def edit
  end

  # POST /drinks
  # POST /drinks.json
  def create
    @drink = Drink.new(drink_params)

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render :show, status: :created, location: @drink }
      else
        format.html { render :new }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drinks/1
  # PATCH/PUT /drinks/1.json
  def update
    respond_to do |format|
      if @drink.update(drink_params)
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink }
      else
        format.html { render :edit }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drinks/1
  # DELETE /drinks/1.json
  def destroy
    @drink.destroy
    respond_to do |format|
      format.html { redirect_to drinks_url, notice: 'Drink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drink
      @drink = Drink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drink_params
      params.require(:drink).permit(:coke, :beer, :water)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:meat, :fish, :pasta)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/drinks/_form.html.erb
<%= form_for(@drink) do |f| %>
  <% if @drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

      <ul>
      <% @drink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :coke %><br>
    <%= f.text_field :coke %>
  </div>
  <div class="field">
    <%= f.label :beer %><br>
    <%= f.text_field :beer %>
  </div>
  <div class="field">
    <%= f.label :water %><br>
    <%= f.text_field :water %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Editing drink</h1>

<%= render 'form' %>

<%= link_to 'Show', @drink %> |
<%= link_to 'Back', drinks_path %>

app/views/drinks/index.html.erb
<h1>Listing drinks</h1>

<table>
  <thead>
    <tr>
      <th>Coke</th>
      <th>Beer</th>
      <th>Water</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drinks.each do |drink| %>
      <tr>
        <td><%= drink.coke %></td>
        <td><%= drink.beer %></td>
        <td><%= drink.water %></td>
        <td><%= link_to 'Show', drink %></td>
        <td><%= link_to 'Edit', edit_drink_path(drink) %></td>
        <td><%= link_to 'Destroy', drink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drink', new_drink_path %>

app/views/drinks/new.html.erb
<h1>New drink</h1>

<%= render 'form' %>

<%= link_to 'Back', drinks_path %>

app/views/drinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coke:</strong>
  <%= @drink.coke %>
</p>

<p>
  <strong>Beer:</strong>
  <%= @drink.beer %>
</p>

<p>
  <strong>Water:</strong>
  <%= @drink.water %>
</p>

<%= link_to 'Edit', edit_drink_path(@drink) %> |
<%= link_to 'Back', drinks_path %>

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meat %><br>
    <%= f.text_field :meat %>
  </div>
  <div class="field">
    <%= f.label :fish %><br>
    <%= f.text_field :fish %>
  </div>
  <div class="field">
    <%= f.label :pasta %><br>
    <%= f.text_field :pasta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>Listing foods</h1>

<table>
  <thead>
    <tr>
      <th>Meat</th>
      <th>Fish</th>
      <th>Pasta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.meat %></td>
        <td><%= food.fish %></td>
        <td><%= food.pasta %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meat:</strong>
  <%= @food.meat %>
</p>

<p>
  <strong>Fish:</strong>
  <%= @food.fish %>
</p>

<p>
  <strong>Pasta:</strong>
  <%= @food.pasta %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>